### ISSUE TITLE
No ev3dev device detected

### ISSUE THREAD

**Issue by laurensvalk** [dlech/vscode-ev3dev-browser#1]
> Any connected ev3dev device should be automatically discovered. No configuration necessary.

I'm probably doing something wrong, but my EV3 does not appear to be detected.

I'm using the ev3dev-stretch snapshot image of 2017-07-25. (I'm no longer using lmscompat, I uninstalled that kernel.)

Connected using ethernet. No problems using SSH outside of VS Code.

![ev3devdevices](https://user-images.githubusercontent.com/12326241/28669977-e838fb56-72d6-11e7-8f1c-9e5f31a97304.png)

I'm using Ubuntu 16.04 and the VS Code About Menu reads:
```
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

**Comment by dlech** [comment]
I made a mistake in the 2017-07-25 image. There are two files in the `/etc/avahi/services/` directory that should have the file extension `.service` instead of `.conf`. 

    sudo mv /etc/avahi/services/*.conf /etc/avahi/service/*.service

It should be fixed in the 2017-07-26 snapshot image.

**Comment by laurensvalk** [comment]
Renaming didn't help, but using the 26'th snapshot does.

Great work!

**Comment by NielsHoffmann** [comment]
I seem to have this same issue with the ev3dev-stretch beta 2 release. Running VS Code 1.30 on an Ubuntu 16.04 laptop. I can ssh into my ev3dev without a problem.
